### PR TITLE
installGit should return a Promise to avoid racing conditions

### PR DESCRIPTION
**Pull request by maikokuppe**

### CODE REVIEW

**Comment by maikokuppe** [comment]
Tests for Node 0.10 and 0.12 are failing because they don't support promises natively.
May I suggest to remove the tests for node 0.10 and 0.12?

**Comment by pimterry** [comment]
Hi @maikokuppe, this looks great! Nice work. Yes, I'm very happy to upgrade in line with [Node LTS](https://github.com/nodejs/LTS), so testing on 4+ would be great. If you make that change and get the tests passing, I'm happy to merge.

As an aside, I don't really use this library myself any more, so it's become basically unmaintained. If you're actively using it, you're probably closer to this than I am - would you be interested in becoming a maintainer? Tiny library, so shouldn't be much work, but that'd let you make changes like this for yourself in future.

**Review by pimterry — APPROVED** [review]

**Comment by maikokuppe** [comment]
Yes, becoming a maintainer sounds good :)
I should mention that I'm probably going to use this library as it is, so I'm probably going to choose the next motivated developer to maintain it if he or she comes around ;)

**Comment by pimterry** [comment]
Merged! I've given you push access to the repo too. Let me know your npm username and I'll add you as a collaborator there as well so you can publish.

**Comment by maikokuppe** [comment]
My npm username is **maiko**

**Comment by pimterry** [comment]
@maikokuppe great, thanks! I've given you publish permissions.

**Comment by pimterry** [comment]
(I think, let me know if you have any trouble)

**Pull request merged**
